// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using learn.it.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace learn.it.Models;

public partial class LearnitDbContext : DbContext
{
    public LearnitDbContext()
    {
    }

    public LearnitDbContext(DbContextOptions<LearnitDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Achievement> Achievements { get; set; }

    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<FlashcardUserProgress> FlashcardUserProgress { get; set; }

    public virtual DbSet<Flashcard> Flashcards { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<Login> Logins { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<StudySet> StudySets { get; set; }

    public virtual DbSet<UserAchievements> UserAchievements { get; set; }

    public virtual DbSet<UserPreferences> UserPreferences { get; set; }

    public virtual DbSet<UserStats> UserStats { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Achievement>(entity =>
        {
            entity.HasKey(e => e.AchievementId).HasName("PK_achievements_achievement_id");

            entity.Property(e => e.AchievementId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Answer>(entity =>
        {
            entity.HasKey(e => e.AnswerId).HasName("PK_answers_answer_id");

            entity.Property(e => e.AnswerId).ValueGeneratedOnAdd();

            entity.HasOne(d => d.Flashcard).WithMany(p => p.Answers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("answers$fk_answers_flashcards1");

            entity.HasOne(d => d.User).WithMany(p => p.Answers).HasConstraintName("answers$fk_answers_users1");
        });

        modelBuilder.Entity<FlashcardUserProgress>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.FlashcardId }).HasName("PK_flashcard_user_progress_user_id");

            entity.HasOne(d => d.Flashcard).WithMany(p => p.FlashcardUserProgress)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("flashcard_user_progress$fk_flashcard_user_progress_flashcards1");

            entity.HasOne(d => d.User).WithMany(p => p.FlashcardUserProgress).HasConstraintName("flashcard_user_progress$fk_flashcard_user_progress_users1");
        });

        modelBuilder.Entity<Flashcard>(entity =>
        {
            entity.HasKey(e => e.FlashcardId).HasName("PK_flashcards_flashcard_id");

            entity.Property(e => e.FlashcardId).ValueGeneratedOnAdd();
            entity.Property(e => e.IsTermText).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.StudySet).WithMany(p => p.Flashcards).HasConstraintName("flashcards$fk_flashcards_study_sets1");
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK_groups_group_id");

            entity.Property(e => e.GroupId).ValueGeneratedOnAdd();

            entity.HasOne(d => d.Owner).WithMany(p => p.GroupsOwner).HasConstraintName("groups$fk_groups_users1");
        });

        modelBuilder.Entity<Login>(entity =>
        {
            entity.HasKey(e => e.LoginId).HasName("PK_logins_login_id");

            entity.Property(e => e.LoginId).ValueGeneratedOnAdd();
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.Logins).HasConstraintName("logins$fk_logins_users");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK_permissions_permission_id");

            entity.Property(e => e.PermissionId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<StudySet>(entity =>
        {
            entity.HasKey(e => e.StudySetId).HasName("PK_study_sets_study_set_id");

            entity.Property(e => e.StudySetId).ValueGeneratedOnAdd();

            entity.HasOne(d => d.Creator).WithMany(p => p.StudySets).HasConstraintName("study_sets$fk_study_sets_users1");

            entity.HasOne(d => d.Group).WithMany(p => p.StudySets).HasConstraintName("study_sets$fk_study_sets_groups1");
        });

        modelBuilder.Entity<UserAchievements>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.AchievementId }).HasName("PK_user_achievements_user_id");

            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Achievement).WithMany(p => p.UserAchievements).HasConstraintName("user_achievements$fk_user_achievements_achievements1");

            entity.HasOne(d => d.User).WithMany(p => p.UserAchievements).HasConstraintName("user_achievements$fk_user_achievements_users1");
        });

        modelBuilder.Entity<UserPreferences>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_user_preferences_user_id");

            entity.Property(e => e.UserId).ValueGeneratedNever();

            entity.HasOne(d => d.User).WithOne(p => p.UserPreferences).HasConstraintName("user_preferences$fk_user_preferences_users1");
        });

        modelBuilder.Entity<UserStats>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_user_stats_user_id");

            entity.Property(e => e.UserId).ValueGeneratedNever();

            entity.HasOne(d => d.User).WithOne(p => p.UserStats).HasConstraintName("user_stats$fk_user_stats_users1");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_users_user_id");

            entity.HasOne(u => u.UserStats).WithOne(us => us.User).HasForeignKey<UserStats>(us => us.UserId);
            entity.HasOne(u => u.UserPreferences).WithOne(us => us.User).HasForeignKey<UserPreferences>(us => us.UserId);

            entity.Property(e => e.UserId).ValueGeneratedOnAdd();
            entity.Property(e => e.Avatar).HasDefaultValueSql("(N'default.png')");
            entity.Property(e => e.CreateTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permissions).WithMany(p => p.Users)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("users$fk_users_permissions1");

            entity.HasMany(d => d.Groups).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UsersHasGroups",
                    r => r.HasOne<Group>().WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("users_has_groups$fk_users_has_groups_groups1"),
                    l => l.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("users_has_groups$fk_users_has_groups_users1"),
                    j =>
                    {
                        j.HasKey("UserId", "GroupId").HasName("PK_users_has_groups_user_id");
                        j.ToTable("users_has_groups", "learnitdb");
                        j.HasIndex(new[] { "GroupId" }, "fk_users_has_groups_groups1_idx");
                        j.HasIndex(new[] { "UserId" }, "fk_users_has_groups_users1_idx");
                        j.IndexerProperty<int>("UserId").HasColumnName("user_id");
                        j.IndexerProperty<int>("GroupId").HasColumnName("group_id");
                    });
        });
        modelBuilder.Seed();
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}