// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("Achievements", Schema = "learnitdb")]
[Index(nameof(Predicate), Name = "predicate_UNIQUE", IsUnique = true)]
public partial class Achievement
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AchievementId { get; set; }

    [StringLength(150)]
    public string Name { get; set; }

    [StringLength(100)]
    public string ImagePath { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    public string Predicate { get; set; }

    [InverseProperty("Achievement")]
    [JsonIgnore]
    public virtual ICollection<UserAchievements> UserAchievements { get; set; } = new List<UserAchievements>();
}