// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("achievements", Schema = "learnitdb")]
public partial class Achievements
{
    [Key]
    [Column("achievement_id")]
    public int AchievementId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(150)]
    public string Name { get; set; }

    [Required]
    [Column("image_url")]
    [StringLength(100)]
    public string ImageUrl { get; set; }

    [Required]
    [Column("description")]
    [StringLength(200)]
    public string Description { get; set; }

    [InverseProperty("Achievement")]
    public virtual ICollection<UserAchievements> UserAchievements { get; set; } = new List<UserAchievements>();
}