// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("answers", Schema = "learnitdb")]
[Index("FlashcardId", Name = "fk_answers_flashcards1_idx")]
[Index("UserId", Name = "fk_answers_users1_idx")]
public partial class Answer
{
    [Key]
    [Column("answer_id")]
    public int AnswerId { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("flashcard_id")]
    public int FlashcardId { get; set; }

    [Column("is_correct")]
    public short IsCorrect { get; set; }

    [Column("answer_time")]
    public int AnswerTime { get; set; }

    [ForeignKey("FlashcardId")]
    [InverseProperty("Answer")]
    public virtual Flashcard Flashcard { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Answer")]
    public virtual User User { get; set; }
}