// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("flashcards", Schema = "learnitdb")]
[Index("StudySetId", Name = "fk_flashcards_study_sets1_idx")]
public partial class Flashcards
{
    [Key]
    [Column("flashcard_id")]
    public int FlashcardId { get; set; }

    [Column("study_set_id")]
    public int StudySetId { get; set; }

    [Required]
    [Column("term")]
    [StringLength(500)]
    public string Term { get; set; }

    [Required]
    [Column("definition")]
    [StringLength(500)]
    public string Definition { get; set; }

    [Column("is_term_text")]
    public short IsTermText { get; set; }

    [InverseProperty("Flashcard")]
    public virtual ICollection<Answers> Answers { get; set; } = new List<Answers>();

    [InverseProperty("Flashcard")]
    public virtual ICollection<FlashcardUserProgress> FlashcardUserProgress { get; set; } = new List<FlashcardUserProgress>();

    [ForeignKey("StudySetId")]
    [InverseProperty("Flashcards")]
    public virtual StudySets StudySet { get; set; }
}