// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("groups", Schema = "learnitdb")]
[Index("OwnerId", Name = "fk_groups_users1_idx")]
public partial class Groups
{
    [Key]
    [Column("group_id")]
    public int GroupId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(150)]
    public string Name { get; set; }

    [Column("owner_id")]
    public int OwnerId { get; set; }

    [ForeignKey("OwnerId")]
    [InverseProperty("Groups")]
    public virtual Users Owner { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<StudySets> StudySets { get; set; } = new List<StudySets>();

    [ForeignKey("GroupId")]
    [InverseProperty("Group")]
    public virtual ICollection<Users> User { get; set; } = new List<Users>();
}