// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace learn.it.Models;

[Table("Logins", Schema = "learnitdb")]
[Index("UserId", Name = "fk_logins_users_idx")]
public partial class Login
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int LoginId { get; private set; }

    [Precision(0)]
    public DateTime Timestamp { get; set; }

    public bool IsSuccessful { get; set; }

    [StringLength(255)]
    public string UserAgent { get; set; }

    [StringLength(45)]
    public string IpAddress { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Logins")]
    public virtual User User { get; set; }
}