// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("logins", Schema = "learnitdb")]
[Index("UserId", Name = "fk_logins_users_idx")]
public partial class Login
{
    [Key]
    [Column("login_id")]
    public int LoginId { get; set; }

    [Column("timestamp")]
    [Precision(0)]
    public DateTime Timestamp { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Login")]
    public virtual User User { get; set; }
}