// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("permissions", Schema = "learnitdb")]
public partial class Permission
{
    [Key]
    [Column("permission_id")]
    public int PermissionId { get; private set; }

    [Required]
    [Column("name")]
    [StringLength(45)]
    public string Name { get; set; }

    [InverseProperty("Permission")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}