// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("study_sets", Schema = "learnitdb")]
[Index("GroupId", Name = "fk_study_sets_groups1_idx")]
[Index("CreatorId", Name = "fk_study_sets_users1_idx")]
public partial class StudySet
{
    [Key]
    [Column("study_set_id")]
    public int StudySetId { get; set; }

    [Required(ErrorMessage = "Study set's name cannot be blank.")]
    [Column("name")]
    [StringLength(100, ErrorMessage = "Study set's name cannot be shorter than 4 and longer than 100 characters.", MinimumLength = 4)]
    public required string Name { get; set; }

    [Column("description")]
    [StringLength(250, ErrorMessage = "Study set's description cannot be longer than 250 characters.")]
    public required string? Description { get; set; }

    //use the static Visibility class as values for this field
    [Required]
    [Column("visibility")]
    [StringLength(7)]
    public required string Visibility { get; set; }

    [ForeignKey("CreatorId")]
    [InverseProperty("StudySet")]
    public virtual User Creator { get; set; }

    [InverseProperty("StudySet")]
    public virtual ICollection<Flashcard> Flashcards { get; set; } = new List<Flashcard>();

    [ForeignKey("GroupId")]
    [InverseProperty("StudySet")]
    public virtual Group Group { get; set; }
}