// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("study_sets", Schema = "learnitdb")]
[Index("GroupId", Name = "fk_study_sets_groups1_idx")]
[Index("CreatorId", Name = "fk_study_sets_users1_idx")]
public partial class StudySets
{
    [Key]
    [Column("study_set_id")]
    public int StudySetId { get; set; }

    [Column("group_id")]
    public int? GroupId { get; set; }

    [Column("creator_id")]
    public int CreatorId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(250)]
    public string Description { get; set; }

    [Required]
    [Column("visibility")]
    [StringLength(7)]
    public string Visibility { get; set; }

    [ForeignKey("CreatorId")]
    [InverseProperty("StudySets")]
    public virtual Users Creator { get; set; }

    [InverseProperty("StudySet")]
    public virtual ICollection<Flashcards> Flashcards { get; set; } = new List<Flashcards>();

    [ForeignKey("GroupId")]
    [InverseProperty("StudySets")]
    public virtual Groups Group { get; set; }
}