// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("study_sets", Schema = "learnitdb")]
[Index("GroupId", Name = "fk_study_sets_groups1_idx")]
[Index("CreatorId", Name = "fk_study_sets_users1_idx")]
public partial class StudySet
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("study_set_id")]
    public int StudySetId { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("description")]
    public string? Description { get; set; }

    [Required]
    [Column("visibility")]
    public Visibility Visibility { get; set; }

    [ForeignKey("CreatorId")]
    [InverseProperty("StudySets")]
    public virtual User Creator { get; set; }

    [InverseProperty("StudySet")]
    public virtual ICollection<Flashcard> Flashcards { get; set; } = new List<Flashcard>();

    [ForeignKey("GroupId")]
    [InverseProperty("StudySets")]
    public virtual Group? Group { get; set; }
}