// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("users", Schema = "learnitdb")]
[Index("PermissionId", Name = "fk_users_permissions1_idx")]
[Index("Email", Name = "users$email_UNIQUE", IsUnique = true)]
[Index("Username", Name = "users$username_UNIQUE", IsUnique = true)]
public partial class Users
{
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    [Column("permission_id")]
    public int PermissionId { get; set; }

    [Required]
    [Column("username")]
    [StringLength(32)]
    public string Username { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [Column("password")]
    [StringLength(100)]
    public string Password { get; set; }

    [Column("create_time")]
    [Precision(0)]
    public DateTime CreateTime { get; set; }

    [Required]
    [Column("avatar")]
    [StringLength(100)]
    public string Avatar { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Answers> Answers { get; set; } = new List<Answers>();

    [InverseProperty("User")]
    public virtual ICollection<FlashcardUserProgress> FlashcardUserProgress { get; set; } = new List<FlashcardUserProgress>();

    [InverseProperty("Owner")]
    public virtual ICollection<Groups> Groups { get; set; } = new List<Groups>();

    [InverseProperty("User")]
    public virtual ICollection<Logins> Logins { get; set; } = new List<Logins>();

    [ForeignKey("PermissionId")]
    [InverseProperty("Users")]
    public virtual Permissions Permission { get; set; }

    [InverseProperty("Creator")]
    public virtual ICollection<StudySets> StudySets { get; set; } = new List<StudySets>();

    [InverseProperty("User")]
    public virtual ICollection<UserAchievements> UserAchievements { get; set; } = new List<UserAchievements>();

    [InverseProperty("User")]
    public virtual UserPreferences UserPreferences { get; set; }

    [InverseProperty("User")]
    public virtual UserStats UserStats { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("User")]
    public virtual ICollection<Groups> Group { get; set; } = new List<Groups>();
}