// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("user_preferences", Schema = "learnitdb")]
[Index("UserId", Name = "fk_user_preferences_users1_idx")]
public partial class UserPreferences
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("user_id")]
    public int UserId { get; private set; }

    [Column("high_contrast_mode")]
    public short HighContrastMode { get; set; } = 0;

    [Column("email_reminders")]
    public short EmailReminders { get; set; } = 0;

    [Column("auto_tts")]
    public short AutoTts { get; set; } = 0;

    [ForeignKey("UserId")]
    [InverseProperty("UserPreferences")]
    public virtual User User { get; set; }
}