// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("UserPreferences", Schema = "learnitdb")]
[Index("UserId", Name = "fk_user_preferences_users1_idx")]
public partial class UserPreferences
{
    [Key, ForeignKey("User")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int UserId { get; private set; }

    public bool HighContrastMode { get; set; } = false;

    public bool AutoTts { get; set; } = false;

    [JsonIgnore]
    public virtual User User { get; set; }
}