// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("users", Schema = "learnitdb")]
[Index("PermissionId", Name = "fk_users_permissions1_idx")]
[Index("Email", Name = "users$email_UNIQUE", IsUnique = true)]
[Index("Username", Name = "users$username_UNIQUE", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("user_id")]
    public int UserId { get; private set; }

    [Column("username")]
    public string Username { get; set; }

    [Column("email")]
    public string Email { get; set; }

    [Column("password")]
    public string Password { get; set; }

    [Column("create_time")]
    [Precision(0)]
    public DateTime CreateTime { get; set; }

    [Column("last_login")]
    [Precision(0)]
    public DateTime? LastLogin { get; set; }

    //this can be null - the database has a default value of "default.png"
    [Column("avatar")]
    public string? Avatar { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [InverseProperty("User")]
    public virtual ICollection<FlashcardUserProgress> FlashcardUserProgress { get; set; } = new List<FlashcardUserProgress>();

    [InverseProperty("Owner")]
    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    [InverseProperty("User")]
    public virtual ICollection<Login> Logins { get; set; } = new List<Login>();

    [ForeignKey("PermissionId")]
    [InverseProperty("User")]
    public virtual Permission Permissions { get; set; }

    [InverseProperty("Creator")]
    public virtual ICollection<StudySet> StudySets { get; set; } = new List<StudySet>();

    [InverseProperty("User")]
    public virtual ICollection<UserAchievements> UserAchievements { get; set; } = new List<UserAchievements>();

    [InverseProperty("User")]
    public virtual UserPreferences UserPreferences { get; set; }

    [InverseProperty("User")]
    public virtual UserStats UserStats { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("User")]
    public virtual ICollection<Group> Group { get; set; } = new List<Group>();
}