// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace learn.it.Models;

[Table("UserStats", Schema = "learnitdb")]
[Index("UserId", Name = "fk_user_stats_users1_idx")]
public partial class UserStats
{
    [Key, ForeignKey("User")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int UserId { get; private set; }

    public int TotalSetsMastered { get; set; }

    public int TotalLoginDays { get; set; }

    public int TotalFlashcardsMastered { get; set; }

    public int ConsecutiveLoginDays { get; set; }

    public int TotalSetsAdded { get; set; }

    public int TotalFlashcardsAdded { get; set; }

    [JsonIgnore]
    public virtual User User { get; set; }
}